### ISSUE TITLE
OnGamespyCheck

### ISSUE THREAD

**Issue by chrisk123999** [urbanyoung/Phasor#48]
Just something that we could use to intercept hash checking when a player joins.

Something along the lines of:
OnGameSpyCheck(hash, valid)
return valid
end

Would provide the hash and whether Gamespy responds with it being valid or not.

**Comment by chrisk123999** [comment]
Would it be possible to still get a function that simply checks if it's valid?  Since we intended to use it on our stat tracker to make it easy to throw out stats for clients that we shouldn't track.

**Comment by urbanyoung** [comment]
Fair enough.

fb35ce9f5699c8a1c159d32e0d867cc0f2fcf10d

**Comment by urbanyoung** [comment]
Updated status codes.. Read docs in this commit 477092bbdb068b581ea7e00a046bd6c2385a695a
