### ISSUE TITLE
The ability to toggle team scrambling - enhancement

### ISSUE THREAD

**Issue by HRShaft** [urbanyoung/Phasor#60]
I do like the way phasor scrambles teams between games.  I would like the ability to turn this feature on and off.  Usually scrims are 2 chosen teams, but on the next map - they are scrambled, must re-adjust teams then do a map reset to unscramble.

If there is already a way to toggle this on/off, it is not documented.

**Comment by urbanyoung** [comment]
Fixed f55fe707752d25bcfffd549946492bf0011ac1a3
