### ISSUE TITLE
Issues with Timers that take more time to execute than the delay.

### ISSUE THREAD

**Issue by th3w1zard1** [urbanyoung/Phasor#69]
If a timer is called every 100ms, and an execution of the timer takes longer than the timer delay (150ms for example), Phasor will call the timer again before the first call is done executing, and that should not happen.

**Comment by urbanyoung** [comment]
Return `false` from the callback and re-register it before doing any processing.

```
function MyTimer()
    my_timer_id = registertimer(delay, "MyTimer")

    ... long operation ...

    return false
end
```
